
version: '3.8'

services:
  yaas-service:
    image: yaas-docker-local-yaas-service:latest
    ports:
      - "80:8080"
    secrets:
      - my_secret
      - node_env
    environment:
      NODE_ENV: production
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

secrets:
  my_secret:
    external: true
  node_env:
    external: true

